<a href="https://colab.research.google.com/github/MARTIN0399/hacking-civico/blob/master/Tareas/03_Exploracion_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p align="center">
<img src="http://codeandomexico.org/resources/img/codeandomexico.png" width="500" alt="Codeando M√©xico"><br>
<a href="http://www.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/website-CodeandoMexico-00D88E.svg"></a>
<a href="http://slack.codeandomexico.org/" target="_blank"><img src="https://img.shields.io/badge/slack-CodeandoMexico-EC0E4F.svg"></a>
</p>
<!-- __ -->

# Curso de Datos Abiertos y Hacking C√≠vico

Este curso tiene como objetivo habilitar las capacidades de la ciudadaniÃÅa y los servidores p√∫blicos en el uso y generaci√≥n de datos abiertos para el bien com√∫n. Puedes encontrar m√°s informaci√≥n [aqu√≠](https://github.com/CodeandoMexico/hacking-civico).

# Exploraci√≥n de datos: COVID-19 en M√©xico

En este cuaderno aprenderemos algunas bases de exploraci√≥n de datos. Los datos a utilizar son los datos abiertos sobre COVID-19 en M√©xico, los cuales pueden ser accedidos directamente desde el portal: https://www.gob.mx/salud/documentos/datos-abiertos-152127

Del portal de datos abiertos podemos encontrar dos enlaces, uno para descargar el conjunto de datos y otro para descargar el diccionario; as√≠ que podemos automatizar el proceso de descarga y descompresi√≥n de la informaci√≥n.

Para obtener los datos, s√≥lo basta que ejecutes la siguiente l√≠nea de c√≥digo, que contiene el comando de descarga de la informaci√≥n.

In [1]:
# Para descargar el conjunto de datos
!wget http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip

# Para descargar el diccionario de los datos
!wget http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip

# Descomprimimos ambas carpetas y movemos archivos
!unzip datos_abiertos_covid19.zip
!unzip diccionario_datos_covid19.zip
!mv ./diccionario_datos_covid19/*.xlsx .
!mv *COVID19MEXICO.csv COVID19MEXICO.csv

# Eliminamos las carpetas comprimidas
!rm -rf diccionario_datos_covid19
!rm datos_abiertos_covid19.zip
!rm diccionario_datos_covid19.zip

--2020-09-11 18:13:57--  http://datosabiertos.salud.gob.mx/gobmx/salud/datos_abiertos/datos_abiertos_covid19.zip
Resolving datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)... 187.210.186.146
Connecting to datosabiertos.salud.gob.mx (datosabiertos.salud.gob.mx)|187.210.186.146|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 31293681 (30M) [application/x-zip-compressed]
Saving to: ‚Äòdatos_abiertos_covid19.zip‚Äô

datos_abiertos_covi 100%[===================>]  29.84M  15.9MB/s    in 1.9s

2020-09-11 18:14:00 (15.9 MB/s) - ‚Äòdatos_abiertos_covid19.zip‚Äô saved [31293681/31293681]

--2020-09-11 18:14:00--  http://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Resolving epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)... 187.191.75.207
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip [following]
--2020-09-11 18:14:01--  https://epidemiologia.salud.gob.mx/gobmx/salud/datos_abiertos/diccionario_datos_covid19.zip
Connecting to epidemiologia.salud.gob.mx (epidemiologia.salud.gob.mx)|187.191.75.207|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 81416 (80K) [application/x-zip-compressed]
Saving to: ‚Äòdiccionario_datos_covid19.zip‚Äô

diccionario_datos_c 100%[===================>]  79.51K   496KB/s    in 0.2s

2020-09-11 18:14:02 (496 KB/s) - ‚Äòdiccionario_datos_covid19.zip‚Äô saved [81416/81416]

Archive:  datos_abiertos_covid19.zip
  inflating: 200910COVID19MEXICO.csv
Archive:  diccionario_datos_covid19.zip
  inflating: diccionario_datos_covid19/Catalogos_0412.xlsx
  inflating: diccionario_datos_covid19/Descriptores_0419.xlsx

Hasta este punto, si abres la barra lateral izaquiera, deber√≠as ser capaz de encontrar los datos:

- `COVID19MEXICO.csv`
- `Catalogos_0412.xlsx`
- `Descriptores_0419.xlsx`

üëàüèº

## Carga

Ahora que tenemos los datos, procederemos a cargarlos. Para cargar los datos, primero importaremos algunos paquetes de Python, pues su funcionalidad nos ser√° muy util.

In [2]:
import statistics

import pandas as pd
import numpy as np

In [4]:
# Especificamos el nombre del archivo por abrir
nombre_archivo = 'COVID19MEXICO.csv'

# Utilizamos la funci√≥n de Pandas para cargar un archivo CSV
data = pd.read_csv(nombre_archivo, encoding='latin-1')

Mostramos la cabeza (primeros elementos del archivo).

In [5]:
data.head()

  FECHA_ACTUALIZACION ID_REGISTRO  ORIGEN  ...  PAIS_NACIONALIDAD  PAIS_ORIGEN  UCI
0          2020-09-10      1e6e4c       2  ...            M√É¬©xico           99   97
1          2020-09-10      113277       2  ...            M√É¬©xico           99   97
2          2020-09-10      058534       2  ...            M√É¬©xico           99   97
3          2020-09-10      05171a       2  ...            M√É¬©xico           99    2
4          2020-09-10      12338a       2  ...            M√É¬©xico           99    2

[5 rows x 35 columns]

Ahora procedemos a cargar el archivo con los descriptores.

In [6]:
nombre_diccionario = 'Descriptores_0419.xlsx'
diccionario = pd.read_excel(nombre_diccionario)

In [7]:
diccionario

    N¬∫  ...                                   FORMATO O FUENTE
0    1  ...                                         AAAA-MM-DD
1    2  ...                                             TEXTO
2    3  ...  CAT√ÅLOGO: ORIGEN                              ...
3    4  ...  CAT√ÅLOGO: SECTOR                              ...
4    5  ...                                CATAL√ìGO: ENTIDADES
5    6  ...       CAT√ÅLOGO: SEXO
6    7  ...                                CATAL√ìGO: ENTIDADES
7    8  ...                                CATAL√ìGO: ENTIDADES
8    9  ...                               CATAL√ìGO: MUNICIPIOS
9   10  ...                           CAT√ÅLOGO: TIPO_PACIENTE
10  11  ...                                         AAAA-MM-DD
11  12  ...                                         AAAA-MM-DD
12  13  ...                                         AAAA-MM-DD
13  14  ...  CAT√ÅLOGO: SI_ NO                              ...
14  15  ...  CAT√ÅLOGO: SI_ NO                              ...
15  16  ...                                   N√öMERICA EN A√ëOS
16  17  ...                            CAT√ÅLOGO: NACIONALIDAD
17  18  ...  CAT√ÅLOGO: SI_ NO                              ...
18  19  ...  CAT√ÅLOGO: SI_ NO                              ...
19  20  ...  CAT√ÅLOGO: SI_ NO                              ...
20  21  ...  CAT√ÅLOGO: SI_ NO                              ...
21  22  ...  CAT√ÅLOGO: SI_ NO                              ...
22  23  ...  CAT√ÅLOGO: SI_ NO                              ...
23  24  ...  CAT√ÅLOGO: SI_ NO                              ...
24  25  ...  CAT√ÅLOGO: SI_ NO                              ...
25  26  ...  CAT√ÅLOGO: SI_ NO                              ...
26  27  ...  CAT√ÅLOGO: SI_ NO                              ...
27  28  ...  CAT√ÅLOGO: SI_ NO                              ...
28  29  ...  CAT√ÅLOGO: SI_ NO                              ...
29  30  ...  CAT√ÅLOGO: SI_ NO                              ...
30  31  ...                                CAT√ÅLOGO: RESULTADO
31  32  ...  CAT√ÅLOGO: SI_ NO                              ...
32  33  ...                               TEXTO, 99= SE IGNORA
33  34  ...                               TEXTO, 97= NO APLICA
34  35  ...  CAT√ÅLOGO: SI_ NO                              ...

[35 rows x 4 columns]

Finalmente, cargamos el rachivo de cat√°logos.

In [9]:
nombre_cat = 'Catalogos_0412.xlsx'
sheets = ['ORIGEN', 'SECTOR', 'SEXO', 'TIPO_PACIENTE', 'SI_NO', 'NACIONALIDAD', 'RESULTADO', 'de ENTIDADES', 'MUNICIPIOS']
catalogues = {}
for sheet in sheets:
  catalogue = pd.read_excel(nombre_cat, sheet_name='Cat√°logo ' + sheet)
  catalogue.columns = catalogue.columns.str.replace(' ', '_')
  catalogue.columns = catalogue.columns.str.replace('.', '')
  catalogue.columns = catalogue.columns.str.lower()
  new_catalogue = {sheet: catalogue}
  catalogues.update(new_catalogue)

In [10]:
catalogues

{'MUNICIPIOS':       clave_municipio        municipio  clave_entidad
 0                   1   AGUASCALIENTES              1
 1                   2         ASIENTOS              1
 2                   3         CALVILLO              1
 3                   4            COS√çO              1
 4                   5      JES√öS MAR√çA              1
 ...               ...              ...            ...
 2496              999  NO ESPECIFICADO             32
 2497              999  NO ESPECIFICADO             36
 2498              997        NO APLICA             97
 2499              998        SE IGNORA             98
 2500              999  NO ESPECIFICADO             99

 [2501 rows x 3 columns], 'NACIONALIDAD':    clave      descripci√≥n
 0      1         MEXICANA
 1      2       EXTRANJERA
 2     99  NO ESPECIFICADO, 'ORIGEN':    clave      descripci√≥n
 0      1            USMER
 1      2   FUERA DE USMER
 2     99  NO ESPECIFICADO, 'RESULTADO':   unnamed:_0              unnamed:_1
 0      CLAVE             DESCRIPCI√ìN
 1          1     Positivo SARS-CoV-2
 2          2  No positivo SARS-CoV-2
 3          3     Resultado pendiente, 'SECTOR':     clave      descripci√≥n
 0       1        CRUZ ROJA
 1       2              DIF
 2       3          ESTATAL
 3       4             IMSS
 4       5   IMSS-BIENESTAR
 5       6           ISSSTE
 6       7        MUNICIPAL
 7       8            PEMEX
 8       9          PRIVADA
 9      10           SEDENA
 10     11            SEMAR
 11     12              SSA
 12     13    UNIVERSITARIO
 13     99  NO ESPECIFICADO, 'SEXO':    clave      descripci√≥n
 0      1            MUJER
 1      2           HOMBRE
 2     99  NO ESPECIFICADO, 'SI_NO':    clave      descripci√≥n
 0      1              SI
 1      2              NO
 2     97        NO APLICA
 3     98        SE IGNORA
 4     99  NO ESPECIFICADO, 'TIPO_PACIENTE':    clave      descripci√≥n
 0      1      AMBULATORIO
 1      2    HOSPITALIZADO
 2     99  NO ESPECIFICADO, 'de ENTIDADES':     clave_entidad               entidad_federativa abreviatura
 0               1                   AGUASCALIENTES          AS
 1               2                  BAJA CALIFORNIA          BC
 2               3              BAJA CALIFORNIA SUR          BS
 3               4                         CAMPECHE          CC
 4               5             COAHUILA DE ZARAGOZA          CL
 5               6                           COLIMA          CM
 6               7                          CHIAPAS          CS
 7               8                        CHIHUAHUA          CH
 8               9                 CIUDAD DE M√âXICO          DF
 9              10                          DURANGO          DG
 10             11                       GUANAJUATO          GT
 11             12                         GUERRERO          GR
 12             13                          HIDALGO          HG
 13             14                          JALISCO          JC
 14             15                           M√âXICO          MC
 15             16              MICHOAC√ÅN DE OCAMPO          MN
 16             17                          MORELOS          MS
 17             18                          NAYARIT          NT
 18             19                       NUEVO LE√ìN          NL
 19             20                           OAXACA          OC
 20             21                           PUEBLA          PL
 21             22                        QUER√âTARO          QT
 22             23                     QUINTANA ROO          QR
 23             24                  SAN LUIS POTOS√ç          SP
 24             25                          SINALOA          SL
 25             26                           SONORA          SR
 26             27                          TABASCO          TC
 27             28                       TAMAULIPAS          TS
 28             29                         TLAXCALA          TL
 29             30  VERACRUZ DE IGNACIO DE LA LLAVE          VZ
 30             31                          YUCAT√ÅN          YN
 31             32                        ZACATECAS          ZS
 32             36         ESTADOS UNIDOS MEXICANOS         EUM
 33             97                        NO APLICA         NaN
 34             98                        SE IGNORA          SI
 35             99                  NO ESPECIFICADO          NE}

In [11]:
catalogues['SEXO']

   clave      descripci√≥n
0      1            MUJER
1      2           HOMBRE
2     99  NO ESPECIFICADO

##Perfilamiento

###Descripci√≥n General

In [12]:
# dimensi√≥n de los datos
print('N√∫mero de filas: {}'.format(data.shape[0]))
print('N√∫mero de columnas: {}'.format(data.shape[1]))

N√∫mero de filas: 1480902
N√∫mero de columnas: 35

In [13]:
# columnas (variables)
data.columns

Index(['FECHA_ACTUALIZACION', 'ID_REGISTRO', 'ORIGEN', 'SECTOR', 'ENTIDAD_UM',
       'SEXO', 'ENTIDAD_NAC', 'ENTIDAD_RES', 'MUNICIPIO_RES', 'TIPO_PACIENTE',
       'FECHA_INGRESO', 'FECHA_SINTOMAS', 'FECHA_DEF', 'INTUBADO', 'NEUMONIA',
       'EDAD', 'NACIONALIDAD', 'EMBARAZO', 'HABLA_LENGUA_INDIG', 'DIABETES',
       'EPOC', 'ASMA', 'INMUSUPR', 'HIPERTENSION', 'OTRA_COM',
       'CARDIOVASCULAR', 'OBESIDAD', 'RENAL_CRONICA', 'TABAQUISMO',
       'OTRO_CASO', 'RESULTADO', 'MIGRANTE', 'PAIS_NACIONALIDAD',
       'PAIS_ORIGEN', 'UCI'],
      dtype='object')

In [14]:
# limpieza del nombre de las columnas, remover espacios, car√°cteres especiales y pasar a min√∫sculas
data.columns = data.columns.str.replace(' ', '_')
data.columns = data.columns.str.replace('.', '')
data.columns = data.columns.str.lower()

In [16]:
# calcular n√∫mero de valores nulos por columna
for col in data.columns:
  print('Valores nulos en "{}": {}'.format(col,data[col].isna().sum()))

Valores nulos en "fecha_actualizacion": 0
Valores nulos en "id_registro": 0
Valores nulos en "origen": 0
Valores nulos en "sector": 0
Valores nulos en "entidad_um": 0
Valores nulos en "sexo": 0
Valores nulos en "entidad_nac": 0
Valores nulos en "entidad_res": 0
Valores nulos en "municipio_res": 0
Valores nulos en "tipo_paciente": 0
Valores nulos en "fecha_ingreso": 0
Valores nulos en "fecha_sintomas": 0
Valores nulos en "fecha_def": 0
Valores nulos en "intubado": 0
Valores nulos en "neumonia": 0
Valores nulos en "edad": 0
Valores nulos en "nacionalidad": 0
Valores nulos en "embarazo": 0
Valores nulos en "habla_lengua_indig": 0
Valores nulos en "diabetes": 0
Valores nulos en "epoc": 0
Valores nulos en "asma": 0
Valores nulos en "inmusupr": 0
Valores nulos en "hipertension": 0
Valores nulos en "otra_com": 0
Valores nulos en "cardiovascular": 0
Valores nulos en "obesidad": 0
Valores nulos en "renal_cronica": 0
Valores nulos en "tabaquismo": 0
Valores nulos en "otro_caso": 0
Valores nulos en "resultado": 0
Valores nulos en "migrante": 0
Valores nulos en "pais_nacionalidad": 0
Valores nulos en "pais_origen": 0
Valores nulos en "uci": 0

In [17]:
# tipos de datos
data.dtypes

fecha_actualizacion    object
id_registro            object
origen                  int64
sector                  int64
entidad_um              int64
sexo                    int64
entidad_nac             int64
entidad_res             int64
municipio_res           int64
tipo_paciente           int64
fecha_ingreso          object
fecha_sintomas         object
fecha_def              object
intubado                int64
neumonia                int64
edad                    int64
nacionalidad            int64
embarazo                int64
habla_lengua_indig      int64
diabetes                int64
epoc                    int64
asma                    int64
inmusupr                int64
hipertension            int64
otra_com                int64
cardiovascular          int64
obesidad                int64
renal_cronica           int64
tabaquismo              int64
otro_caso               int64
resultado               int64
migrante                int64
pais_nacionalidad      object
pais_origen            object
uci                     int64
dtype: object

###Limpieza

In [18]:
# convertimos a fecha algunas columnas
def cast_datetime_cols(df):
    timestamp_cols = [col for col in df.columns if "fecha" in col]
    df[timestamp_cols] = df[timestamp_cols].apply(lambda date_col: pd.to_datetime(date_col, errors="coerce"), axis=0)
    return df

data = cast_datetime_cols(data)

In [19]:
data.head()

  fecha_actualizacion id_registro  origen  ...  pais_nacionalidad  pais_origen  uci
0          2020-09-10      1e6e4c       2  ...            M√É¬©xico           99   97
1          2020-09-10      113277       2  ...            M√É¬©xico           99   97
2          2020-09-10      058534       2  ...            M√É¬©xico           99   97
3          2020-09-10      05171a       2  ...            M√É¬©xico           99    2
4          2020-09-10      12338a       2  ...            M√É¬©xico           99    2

[5 rows x 35 columns]

In [20]:
# unimos los datos con los catalogos para tener mejor entendimiento de ellos
data = (
    # unimos con el cat√°logo MUNICIPIOS y ENTIDADES
    data.merge(catalogues['de ENTIDADES'], how='left', left_on='entidad_res', right_on='clave_entidad').
    drop(columns=['entidad_res', 'abreviatura']).
    rename(columns={'entidad_federativa':'entidad_res'}).
    merge(catalogues['MUNICIPIOS'], how='left', left_on=['clave_entidad','municipio_res'], right_on=['clave_entidad','clave_municipio']).
    drop(columns=['municipio_res', 'clave_entidad', 'clave_municipio']).
    rename(columns={'municipio':'municipio_res'})
)

In [21]:
# unimos con el cat√°logo de ENTIDADES
entidades_cols = [col for col in data.columns if "entidad" in col and col != 'entidad_res']
for col in entidades_cols:
    data = (
        data.merge(catalogues['de ENTIDADES'], how='left', left_on=col, right_on='clave_entidad').
        drop(columns=[col, 'abreviatura', 'clave_entidad']).
        rename(columns={'entidad_federativa':col})
    )

In [22]:
# unimos con el cat√°logo SI_NO
sino_cols = ['intubado', 'neumonia', 'embarazo', 'habla_lengua_indig', 'diabetes', 'epoc', 'asma', 'inmusupr',
             'hipertension', 'otra_com', 'cardiovascular', 'obesidad', 'renal_cronica', 'tabaquismo', 
             'otro_caso', 'migrante', 'uci']
for col in sino_cols:
    data = (
        data.merge(catalogues['SI_NO'], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripci√≥n':col})
    )

> **Nota:**
>
> Si ejecutaste una versi√≥n previa del cuaderno, notar√°s que en la siguiente secci√≥n aparec√≠a un error. A continuaci√≥n dejamos como un peque√±o par√©ntesis un poco m√°s de limpieza sobre el cuaderno.

1. Corregimos el nombre de las columnas:

In [23]:
catalogues['RESULTADO'].columns

Index(['unnamed:_0', 'unnamed:_1'], dtype='object')

In [31]:
catalogues['RESULTADO'].columns = ['clave', 'descripci√≥n']
catalogues['RESULTADO'].columns

Index(['clave', 'descripci√≥n'], dtype='object')

2. Removemos la (primera) fila que no nos es √∫til.

In [35]:
catalogues['RESULTADO'] = catalogues['RESULTADO'].drop(index=0)

KeyError: ignored

3. Convertimos el tipo de dato.

In [36]:
catalogues['RESULTADO']['clave'] = catalogues['RESULTADO']['clave'].astype(int)

> Fin del par√©ntesis. Hasta esta secci√≥n, esta parte de limpieza permite continuar con el proceso de manera normal.

In [37]:
# unimos otras columnnas que comparten l√≥gica
other_cols = ['origen', 'sector', 'sexo', 'tipo_paciente', 'nacionalidad', 'resultado']
for col, cat in zip(other_cols, [x.upper() for x in other_cols]):
    data = (
        data.merge(catalogues[cat], how='left', left_on=col, right_on='clave').
        drop(columns=[col, 'clave']).
        rename(columns={'descripci√≥n':col})
    )

In [38]:
# creamos algunas variables que podr√≠an ser √∫tiles despu√©s
data['defuncion'] = ~data.fecha_def.isna()
data['mes_def'] = data.fecha_def.dt.month
data['a√±o_def'] = data.fecha_def.dt.year
data['mes_ingreso'] = data.fecha_ingreso.dt.month
data['a√±o_ingreso'] = data.fecha_ingreso.dt.year

In [39]:
data.head()

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-09-10      1e6e4c  ...           4        2020
1          2020-09-10      113277  ...           5        2020
2          2020-09-10      058534  ...           4        2020
3          2020-09-10      05171a  ...           4        2020
4          2020-09-10      12338a  ...           4        2020

[5 rows x 40 columns]

###Filtros

**Distintas formas de filtrar lo mismo**

In [40]:
# usando query
data.query('nacionalidad == "MEXICANA"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-09-10      1e6e4c  ...           4        2020
1          2020-09-10      113277  ...           5        2020

[2 rows x 40 columns]

In [41]:
# haciendo referencia a la columna como √≠ndice
data[data['nacionalidad'] == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-09-10      1e6e4c  ...           4        2020
1          2020-09-10      113277  ...           5        2020

[2 rows x 40 columns]

In [42]:
# seleccionando directamente la columna que queremos filtrar
data[data.nacionalidad == 'MEXICANA'].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
0          2020-09-10      1e6e4c  ...           4        2020
1          2020-09-10      113277  ...           5        2020

[2 rows x 40 columns]

**Filtrado m√∫ltiple**

In [44]:
# usando query podemos poner en el string del query todas las condiciones que queramos
data.query('nacionalidad == "MEXICANA" & entidad_res == "CIUDAD DE M√âXICO"').head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
2          2020-09-10      058534  ...           4        2020
3          2020-09-10      05171a  ...           4        2020

[2 rows x 40 columns]

In [46]:
# usando el filtrado tradicional debemos encerrar en par√©ntesis cada condici√≥n que queremos que cumpla nuestro filtro
data[(data['nacionalidad'] == "MEXICANA") & (data.entidad_res == "CIUDAD DE M√âXICO")].head(2)

  fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
2          2020-09-10      058534  ...           4        2020
3          2020-09-10      05171a  ...           4        2020

[2 rows x 40 columns]

###Res√∫menes

In [48]:
# una columna, una m√©trica
data.groupby('sexo').edad.mean()

sexo
HOMBRE    42.710065
MUJER     41.666225
Name: edad, dtype: float64

In [49]:
# una columna, varias m√©tricas
data.groupby('sexo').agg({'edad': ['min','mean','max']})

       edad
        min       mean  max
sexo
HOMBRE    0  42.710065  120
MUJER     0  41.666225  120

In [50]:
# varias columnas, una m√©trica
data.groupby('sexo').agg({'edad': 'mean', 'mes_ingreso': 'mean', 'mes_def': 'mean'})

             edad  mes_ingreso   mes_def
sexo
HOMBRE  42.710065     6.687094  6.470030
MUJER   41.666225     6.761805  6.540446

In [51]:
# varias columnas, varias m√©tricas
data.groupby('sexo').agg({'edad': ['min','mean','max'], 'mes_ingreso': ['min','mean','max'], 'mes_def': ['min','mean','max']})

       edad                 mes_ingreso               mes_def
        min       mean  max         min      mean max     min      mean  max
sexo
HOMBRE    0  42.710065  120           1  6.687094   9     1.0  6.470030  9.0
MUJER     0  41.666225  120           1  6.761805   9     1.0  6.540446  9.0

###Descripci√≥n por Tipo

In [52]:
# Filtrar por tipos generales (categ√≥ricas y num√©ricas)
numerical = data.select_dtypes(include='number')
categorical = data.select_dtypes(include=['object', 'bool', 'category', 'datetime64[ns]'])

In [53]:
numerical.head()

   edad  mes_def  a√±o_def  mes_ingreso  a√±o_ingreso
0    31      NaN      NaN            4         2020
1    31      NaN      NaN            5         2020
2    34      NaN      NaN            4         2020
3    34      4.0   2020.0            4         2020
4    44      NaN      NaN            4         2020

In [ ]:
categorical.head()

  fecha_actualizacion id_registro  ...            resultado defuncion
0          2020-09-03      097d14  ...  Positivo SARS-CoV-2     False
1          2020-09-03      1b7adb  ...  Positivo SARS-CoV-2      True
2          2020-09-03      11daaa  ...  Positivo SARS-CoV-2     False
3          2020-09-03      17c9eb  ...  Positivo SARS-CoV-2     False
4          2020-09-03      14f12c  ...  Positivo SARS-CoV-2     False

[5 rows x 35 columns]

In [55]:
# para conocer todos los tipo de datos
?data.select_dtypes

####Categ√≥ricas

In [56]:
# Cardinalidad - Valores √∫nicos por columna
for col in categorical.columns:
  print('Valores √∫nicos en "{}": {}'.format(col,categorical[col].nunique()))

Valores √∫nicos en "fecha_actualizacion": 1
Valores √∫nicos en "id_registro": 1480902
Valores √∫nicos en "fecha_ingreso": 254
Valores √∫nicos en "fecha_sintomas": 254
Valores √∫nicos en "fecha_def": 199
Valores √∫nicos en "pais_nacionalidad": 119
Valores √∫nicos en "pais_origen": 77
Valores √∫nicos en "entidad_res": 32
Valores √∫nicos en "municipio_res": 2162
Valores √∫nicos en "entidad_um": 32
Valores √∫nicos en "entidad_nac": 33
Valores √∫nicos en "intubado": 4
Valores √∫nicos en "neumonia": 3
Valores √∫nicos en "embarazo": 4
Valores √∫nicos en "habla_lengua_indig": 3
Valores √∫nicos en "diabetes": 3
Valores √∫nicos en "epoc": 3
Valores √∫nicos en "asma": 3
Valores √∫nicos en "inmusupr": 3
Valores √∫nicos en "hipertension": 3
Valores √∫nicos en "otra_com": 3
Valores √∫nicos en "cardiovascular": 3
Valores √∫nicos en "obesidad": 3
Valores √∫nicos en "renal_cronica": 3
Valores √∫nicos en "tabaquismo": 3
Valores √∫nicos en "otro_caso": 3
Valores √∫nicos en "migrante": 3
Valores √∫nicos en "uci": 4
Valores √∫nicos en "origen": 2
Valores √∫nicos en "sector": 14
Valores √∫nicos en "sexo": 2
Valores √∫nicos en "tipo_paciente": 2
Valores √∫nicos en "nacionalidad": 2
Valores √∫nicos en "resultado": 3
Valores √∫nicos en "defuncion": 2

In [58]:
# Unicidad - proporci√≥n de valores √∫nicos por columna
total = data.shape[0]
for col in categorical.columns:
  print('Porcentaje de valores √∫nicos en "{}": {}%'.format(col,round(categorical[col].nunique()/total*100,2)))

Porcentaje de valores √∫nicos en "fecha_actualizacion": 0.0%
Porcentaje de valores √∫nicos en "id_registro": 100.0%
Porcentaje de valores √∫nicos en "fecha_ingreso": 0.02%
Porcentaje de valores √∫nicos en "fecha_sintomas": 0.02%
Porcentaje de valores √∫nicos en "fecha_def": 0.01%
Porcentaje de valores √∫nicos en "pais_nacionalidad": 0.01%
Porcentaje de valores √∫nicos en "pais_origen": 0.01%
Porcentaje de valores √∫nicos en "entidad_res": 0.0%
Porcentaje de valores √∫nicos en "municipio_res": 0.15%
Porcentaje de valores √∫nicos en "entidad_um": 0.0%
Porcentaje de valores √∫nicos en "entidad_nac": 0.0%
Porcentaje de valores √∫nicos en "intubado": 0.0%
Porcentaje de valores √∫nicos en "neumonia": 0.0%
Porcentaje de valores √∫nicos en "embarazo": 0.0%
Porcentaje de valores √∫nicos en "habla_lengua_indig": 0.0%
Porcentaje de valores √∫nicos en "diabetes": 0.0%
Porcentaje de valores √∫nicos en "epoc": 0.0%
Porcentaje de valores √∫nicos en "asma": 0.0%
Porcentaje de valores √∫nicos en "inmusupr": 0.0%
Porcentaje de valores √∫nicos en "hipertension": 0.0%
Porcentaje de valores √∫nicos en "otra_com": 0.0%
Porcentaje de valores √∫nicos en "cardiovascular": 0.0%
Porcentaje de valores √∫nicos en "obesidad": 0.0%
Porcentaje de valores √∫nicos en "renal_cronica": 0.0%
Porcentaje de valores √∫nicos en "tabaquismo": 0.0%
Porcentaje de valores √∫nicos en "otro_caso": 0.0%
Porcentaje de valores √∫nicos en "migrante": 0.0%
Porcentaje de valores √∫nicos en "uci": 0.0%
Porcentaje de valores √∫nicos en "origen": 0.0%
Porcentaje de valores √∫nicos en "sector": 0.0%
Porcentaje de valores √∫nicos en "sexo": 0.0%
Porcentaje de valores √∫nicos en "tipo_paciente": 0.0%
Porcentaje de valores √∫nicos en "nacionalidad": 0.0%
Porcentaje de valores √∫nicos en "resultado": 0.0%
Porcentaje de valores √∫nicos en "defuncion": 0.0%

In [59]:
# Moda - valor que m√°s se repite en cada columna excepto los indicadores √∫nicos
for col in categorical.drop(columns='id_registro').columns:
  print('Valor m√°s popular en "{}": {}'.format(col, statistics.mode(categorical[col])))

Valor m√°s popular en "fecha_actualizacion": 2020-09-10 00:00:00
Valor m√°s popular en "fecha_ingreso": 2020-07-20 00:00:00
Valor m√°s popular en "fecha_sintomas": 2020-07-20 00:00:00
Valor m√°s popular en "fecha_def": NaT
Valor m√°s popular en "pais_nacionalidad": M√É¬©xico
Valor m√°s popular en "pais_origen": 99
Valor m√°s popular en "entidad_res": CIUDAD DE M√âXICO
Valor m√°s popular en "municipio_res": IZTAPALAPA
Valor m√°s popular en "entidad_um": CIUDAD DE M√âXICO
Valor m√°s popular en "entidad_nac": CIUDAD DE M√âXICO
Valor m√°s popular en "intubado": NO APLICA
Valor m√°s popular en "neumonia": NO
Valor m√°s popular en "embarazo": NO
Valor m√°s popular en "habla_lengua_indig": NO
Valor m√°s popular en "diabetes": NO
Valor m√°s popular en "epoc": NO
Valor m√°s popular en "asma": NO
Valor m√°s popular en "inmusupr": NO
Valor m√°s popular en "hipertension": NO
Valor m√°s popular en "otra_com": NO
Valor m√°s popular en "cardiovascular": NO
Valor m√°s popular en "obesidad": NO
Valor m√°s popular en "renal_cronica": NO
Valor m√°s popular en "tabaquismo": NO
Valor m√°s popular en "otro_caso": SI
Valor m√°s popular en "migrante": NO ESPECIFICADO
Valor m√°s popular en "uci": NO APLICA
Valor m√°s popular en "origen": FUERA DE USMER
Valor m√°s popular en "sector": SSA
Valor m√°s popular en "sexo": MUJER
Valor m√°s popular en "tipo_paciente": AMBULATORIO
Valor m√°s popular en "nacionalidad": MEXICANA
Valor m√°s popular en "resultado": No positivo SARS-CoV-2
Valor m√°s popular en "defuncion": False

####Num√©ricas

In [60]:
numerical.describe()

               edad       mes_def  a√±o_def   mes_ingreso  a√±o_ingreso
count  1.480902e+06  88994.000000  88994.0  1.480902e+06    1480902.0
mean   4.217925e+01      6.495696   2020.0  6.725086e+00       2020.0
std    1.680574e+01      1.288203      0.0  1.373313e+00          0.0
min    0.000000e+00      1.000000   2020.0  1.000000e+00       2020.0
25%    3.000000e+01      6.000000   2020.0  6.000000e+00       2020.0
50%    4.100000e+01      7.000000   2020.0  7.000000e+00       2020.0
75%    5.300000e+01      7.000000   2020.0  8.000000e+00       2020.0
max    1.200000e+02      9.000000   2020.0  9.000000e+00       2020.0

##An√°lisis Exploratorio

En esta secci√≥n responderemos algunas preguntas sobre el set de datos usando las herramientas que hemos visto hasta ahora

In [61]:
# ¬øCu√°ntas pruebas por origen se realizan?
data.groupby('origen').id_registro.count()

origen
FUERA DE USMER    989964
USMER             490938
Name: id_registro, dtype: int64

In [62]:
data.origen.value_counts()

FUERA DE USMER    989964
USMER             490938
Name: origen, dtype: int64

In [63]:
# ¬øCu√°ntas pruebas por sector se realizan?
data.sector.value_counts()

SSA                922584
IMSS               379863
ISSSTE              56023
PRIVADA             54636
ESTATAL             26777
PEMEX               12764
IMSS-BIENESTAR      10045
SEMAR                7709
SEDENA               7243
MUNICIPAL            1183
UNIVERSITARIO        1006
DIF                   839
CRUZ ROJA             222
NO ESPECIFICADO         8
Name: sector, dtype: int64

In [64]:
# ¬øCu√°ntos pacientes por sexo tenemos?
data.sexo.value_counts()

MUJER     753076
HOMBRE    727826
Name: sexo, dtype: int64

In [65]:
# ¬øCu√°l es la proporci√≥n de los pacientes por sexo?
data.sexo.value_counts(normalize=True)

MUJER     0.508525
HOMBRE    0.491475
Name: sexo, dtype: float64

In [66]:
# ¬øCu√°l es la proporci√≥n de resultados de las pruebas?
data.resultado.value_counts(normalize=True)

No positivo SARS-CoV-2    0.501227
Positivo SARS-CoV-2       0.440518
Resultado pendiente       0.058255
Name: resultado, dtype: float64

In [67]:
# ¬øCu√°ntas pruebas positivas tenemos en el set?
data[data.resultado == 'Positivo SARS-CoV-2'].id_registro.count()

652364

In [68]:
# ¬øCu√°ntos casos positivos tenemos por mes?
data[data.resultado == 'Positivo SARS-CoV-2'].mes_ingreso.value_counts().sort_index()

1         2
2         8
3      2530
4     26561
5     86513
6    152881
7    199253
8    155229
9     29387
Name: mes_ingreso, dtype: int64

In [69]:
# ¬øCu√°l es el resultado de las pruebas por sexo?
data.groupby(['sexo','resultado'])['id_registro'].count()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    345156
        Positivo SARS-CoV-2       340808
        Resultado pendiente        41862
MUJER   No positivo SARS-CoV-2    397112
        Positivo SARS-CoV-2       311556
        Resultado pendiente        44408
Name: id_registro, dtype: int64

In [70]:
data.groupby('sexo').resultado.value_counts()

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    345156
        Positivo SARS-CoV-2       340808
        Resultado pendiente        41862
MUJER   No positivo SARS-CoV-2    397112
        Positivo SARS-CoV-2       311556
        Resultado pendiente        44408
Name: resultado, dtype: int64

In [71]:
# ¬øQu√© proporci√≥n de resultados de pruebas tenemos por sexo?
data.groupby('sexo').resultado.value_counts(normalize=True)

sexo    resultado
HOMBRE  No positivo SARS-CoV-2    0.474229
        Positivo SARS-CoV-2       0.468255
        Resultado pendiente       0.057516
MUJER   No positivo SARS-CoV-2    0.527320
        Positivo SARS-CoV-2       0.413711
        Resultado pendiente       0.058969
Name: resultado, dtype: float64

In [72]:
# ¬øCu√°l es la edad de los pacientes por sexo?
data.groupby('sexo').edad.describe()

           count       mean        std  min   25%   50%   75%    max
sexo
HOMBRE  727826.0  42.710065  17.121450  0.0  30.0  41.0  54.0  120.0
MUJER   753076.0  41.666225  16.478642  0.0  30.0  40.0  52.0  120.0

In [73]:
def q25(x):
  return x.quantile(0.25)

def q75(x):
  return x.quantile(0.75)

data.groupby('sexo').agg({'edad': ['min', q25, 'median', q75, 'max']})

       edad
        min q25 median q75  max
sexo
HOMBRE    0  30     41  54  120
MUJER     0  30     40  52  120

In [74]:
# ¬øCu√°l es la edad de los pacientes dependiendo de si son intubados o no?
data.groupby('intubado').edad.describe()

                     count       mean        std  min    25%   50%   75%    max
intubado
NO                218941.0  53.306014  19.657083  0.0  42.00  55.0  67.0  118.0
NO APLICA        1222384.0  39.702625  15.069096  0.0  29.00  38.0  49.0  120.0
NO ESPECIFICADO      190.0  54.189474  16.975422  0.0  43.25  57.0  65.0   92.0
SI                 39387.0  57.133293  17.876950  0.0  48.00  59.0  69.0  108.0

In [75]:
data.groupby('intubado').agg({'edad': ['min', q25, 'median', q75, 'max']})

                edad
                 min    q25 median q75  max
intubado
NO                 0  42.00     55  67  118
NO APLICA          0  29.00     38  49  120
NO ESPECIFICADO    0  43.25     57  65   92
SI                 0  48.00     59  69  108

In [76]:
# ¬øCu√°l es la edad m√°xima y cu√°l es la m√≠nima de los pacientes fallecidos?
edad_def_max = data[data.defuncion].edad.max()
data[data.defuncion & (data.edad == edad_def_max)]

       fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
610999          2020-09-10      1b7b20  ...           5        2020

[1 rows x 40 columns]

In [77]:
edad_def_min = data[data.defuncion].edad.min()
data[data.defuncion & (data.edad == edad_def_min)]

        fecha_actualizacion id_registro  ... mes_ingreso a√±o_ingreso
1304             2020-09-10      083c34  ...           5        2020
7724             2020-09-10      02f8e2  ...           5        2020
36522            2020-09-10      1cc0ea  ...           4        2020
38595            2020-09-10      1b82ee  ...           5        2020
44941            2020-09-10      053398  ...           6        2020
...                     ...         ...  ...         ...         ...
1426732          2020-09-10      19416e  ...           8        2020
1433004          2020-09-10      1e94e4  ...           8        2020
1440479          2020-09-10      00f39c  ...           7        2020
1470508          2020-09-10      3b8095  ...           9        2020
1477741          2020-09-10      07cf0b  ...           8        2020

[250 rows x 40 columns]

In [78]:
# ¬øCu√°l es la edad de los pacientes que fallecen?
data.groupby('defuncion').edad.describe()

               count       mean        std  min   25%   50%   75%    max
defuncion
False      1391908.0  40.918554  16.100920  0.0  29.0  40.0  51.0  120.0
True         88994.0  61.897060  15.216359  0.0  53.0  63.0  72.0  109.0

In [79]:
# ¬øCu√°ntas defunciones tenemos por mes?
data[data.defuncion].mes_def.value_counts().sort_index()

1.0        6
2.0       12
3.0      232
4.0     5294
5.0    16094
6.0    21434
7.0    23765
8.0    18666
9.0     3491
Name: mes_def, dtype: int64

In [80]:
# ¬øCu√°l es la proporci√≥n de di√°beticos para las defunciones?
data.groupby('diabetes').defuncion.value_counts(normalize=True)

diabetes   defuncion
NO         False        0.957851
           True         0.042149
SE IGNORA  False        0.871063
           True         0.128937
SI         False        0.812911
           True         0.187089
Name: defuncion, dtype: float64

In [81]:
# ¬øCu√°l es la proporci√≥n de asm√°ticos para las defunciones?
data.groupby('asma').defuncion.value_counts(normalize=True)

asma       defuncion
NO         False        0.939578
           True         0.060422
SE IGNORA  False        0.864160
           True         0.135840
SI         False        0.957878
           True         0.042122
Name: defuncion, dtype: float64